#ifndef CONSTANTS_H
#define CONSTANTS_H

const int MOD = 1000000007;

const int LEVEL_WIDTH = 5120 * 2;
const int LEVEL_HEIGHT = 1280;

const int SCREEN_WIDTH = 1368;
const int SCREEN_HEIGHT = 768;

const int TILE_WIDTH = 64;
const int TILE_HEIGHT = 64;
const int TILE_TEXTURE_WIDTH = 64;
const int TILE_TEXTURE_HEIGHT = 64;
const int TOTAL_TILES = 1600 * 2;
const int TILE_SET_WIDTH = 960;
const int TOTAL_WALL_TILES = 16;
const double PI = 3.1415926535897932384626433832795;
const int SCREEN_FPS = 60;
const int SCREEN_TICKS_PER_FRAME = 1000 / SCREEN_FPS;

enum TextureID
{
    PLAYER_TEXTURE,
    TILE_TEXTURE,
    FIRE_ATTACK_TEXTURE,
    HAMMER_SKILL_TEXTURE,
    SKELETON_TEXTURE,
    HP_TEXTURE,
    MP_TEXTURE,
    ATKP_TEXTURE,
    BOSS_TEXTURE,
    FIRE_BALL_TEXTURE,
    MENU_BACKGROUND_TEXTURE,
    MENU_BUTTON_TEXTURE,
    MENU_TITLE_TEXTURE,
    SUBMENU_BACKGROUND_TEXTURE,
    SUBMENU_BUTTON_TEXTURE,
    SUBMENU_TITLE_TEXTURE,
    DOOR_TEXTURE,
    SECRET_AREA_TEXTURE,
    KEY_TEXTURE,
    CHEST_TEXTURE,
    HP_BUFF_TEXTURE,
    ATK_BUFF_TEXTURE,
    SKILL_UNLOCK_TEXTURE,
    TOTAL_TEXTURE
};

enum MenuSoundEffect
{
    SELECT_BUTTON_SOUND,
    TOTAL_MENU_SOUND_EFFECT
};

enum PlayerSoundEffect
{
    ATTACK_SOUND,
    DASH_SOUND,
    JUMP_SOUND,
    LAND_SOUND,
    WALK_SOUND,
    TAKE_HIT_SOUND,
    HP_BUFF_SOUND,
    ATK_BUFF_SOUND,
    PAUSE_SOUND,
    TOTAL_PLAYER_SOUND_EFFECT
};

enum TileSprites
{
    TILE_TRAP = 242,
    TOTAL_TILE_SPRITES = 270
};

enum GameState
{
    STATE_PLAY,
    STATE_MENU,
    STATE_AGAIN,
    STATE_PAUSE_MENU,
    STATE_GAME_OVER_MENU,
    STATE_WIN_MENU,
    TOTAL_STATE
};

#endif